import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Nav/Navbar";
import { Provider } from "react-redux";
import { store } from "@/Redux/store";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import Footer from "@/components/Shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thyrocare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
          <div className="max-w-screen-xl mx-auto">
            <ReduxProvider>{children}</ReduxProvider>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
